version: 3
# define: &endpoint process.env.HASURA_GRAPHQL_ENDPOINT
# define: &admin_secret process.env.HASURA_GRAPHQL_ADMIN_SECRET
endpoint: ${HASURA_GRAPHQL_ENDPOINT}
admin_secret: ${HASURA_GRAPHQL_ADMIN_SECRET}
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000